Data Preprocessing

Introduction to NumPy & Pandas

In [ ]:
#basics
import numpy as np

Numpy Datatypes

In [2]:
list=[1,2,3,4]
print(list)
print(type(list))

[1, 2, 3, 4]
<class 'list'>


In [5]:
arr=np.array([1,2,3,4])
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [6]:
arr=np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Let's see the different dimentional array
1-D Array

In [8]:
arr=np.array(42)
print(arr)

42


In [9]:
arr=np.array([1,2,3,4,5])
arr1=np.asarray([1,2,3,4,5])
print(arr)
print(arr1)

[1 2 3 4 5]
[1 2 3 4 5]


2-D Array

In [10]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [17]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
#print the dimension of array
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [21]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
c=np.array([[13,14,15],[16,17,18]])
#print the arrays
print(a)
#dimension of array
print(a.ndim)
print(b)
print(b.ndim)
print(c)
print(c.ndim)

[[1 2 3]
 [4 5 6]]
2
[[ 7  8  9]
 [10 11 12]]
2
[[13 14 15]
 [16 17 18]]
2


NPY File Saving

In [24]:
np.save('my_array.npy',a)
b=np.load('my_array.npy')
print(b)

[[1 2 3]
 [4 5 6]]
