Data Preprocessing

Introduction to NumPy & Pandas

In [ ]:
#basics
import numpy as np

Numpy Datatypes

In [2]:
list=[1,2,3,4]
print(list)
print(type(list))

[1, 2, 3, 4]
<class 'list'>


In [5]:
arr=np.array([1,2,3,4])
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [6]:
arr=np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Let's see the different dimentional array
1-D Array

In [8]:
arr=np.array(42)
print(arr)

42


In [9]:
arr=np.array([1,2,3,4,5])
arr1=np.asarray([1,2,3,4,5])
print(arr)
print(arr1)

[1 2 3 4 5]
[1 2 3 4 5]


2-D Array

In [10]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [17]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
#print the dimension of array
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [21]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
c=np.array([[13,14,15],[16,17,18]])
#print the arrays
print(a)
#dimension of array
print(a.ndim)
print(b)
print(b.ndim)
print(c)
print(c.ndim)

[[1 2 3]
 [4 5 6]]
2
[[ 7  8  9]
 [10 11 12]]
2
[[13 14 15]
 [16 17 18]]
2


NPY File Saving

In [24]:
np.save('my_array.npy',a)
b=np.load('my_array.npy')
print(b)

[[1 2 3]
 [4 5 6]]


Pickle
savetxt()

In [25]:
a=np.array([1,2,3,4,5])
np.savetxt('my_array.txt',a)
b=np.loadtxt('my_array.txt')
print(b)
print(type(b))

[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>


Indexing

In [26]:
arr=np.arange(1,10,2)
print("Elements of array:",arr)
arr1=arr[np.array([4,0,2,-1,-2])]
print("Indexed Elements of array arr:",arr1)

Elements of array: [1 3 5 7 9]
Indexed Elements of array arr: [9 1 5 9 7]


Indexing in 1-D

In [ ]:
arr=np.arange(12)
arr1=np.arange(4)
print("Array arr11: ",arr1)
print("Element at index 0: ",arr1[0])
print("Element at index 1: ",arr1[1])

Array arr11:  [0 1 2 3]
Element at index 0:  0
Element at index 1:  1


Indexing in 2-D

In [31]:
arr=np.arange(12)
arr1=arr.reshape(3,4)
print(arr)
print("Array arr1: \n",arr1)
print("Element at 0th row and 0th column: ",arr1[0,0])
print("Element at 1st row and 2nd column: ",arr1[1,2])
print("Element at 2nd row and 2nd column: ",arr1[2,2])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Array arr1: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Element at 0th row and 0th column:  0
Element at 1st row and 2nd column:  6
Element at 2nd row and 2nd column:  10


Indexing in 3-D

(*Explained how to read a code also)

In [32]:
arr=np.arange(12)
arr1=arr.reshape(2,2,3)
print("Array arr1: \n",arr1)
print("Element: ",arr1[1,0,2])

Array arr1: 
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Element:  8


Slicing an Array

In [45]:
arr=np.arange(12)
arr1=arr.reshape(3,4)
print("Array arr1: \n",arr1)
print("\n")
print("Elements at 1st row and 1st column upto last column:",arr1[1,1:4])
print("Elements at 2nd row and 0th column upto last column:",arr1[2:,0:4])

Array arr1: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Elements at 1st row and 1st column upto last column: [5 6 7]
Elements at 2nd row and 0th column upto last column: [[ 8  9 10 11]]


Broadcasting [Skipped]

Structured Arrays

In [56]:
a=np.array([('Shiva Ganesh', 22, 21.0), ('Talikota',7, 29.0)],
           dtype = [('Name', (np. str_, 10)), ('Age', np.int32), ('Weight', np.float64)])
print(a)

[('Shiva Gane', 22, 21.) ('Talikota',  7, 29.)]
