In [1]:
# Defining a numpy array
import numpy as np 
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [38]:

import numpy as np
arr = np.arange(10, 100) # Returs an array of numbers from 2 to 20 excluding 20
print(arr)
print(type(arr))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
<class 'numpy.ndarray'>


In [5]:
import numpy as np
x=np.empty([2,4],dtype=int)
print(x)

[[       1        1        0      493]
 [    1412        0 16777984      493]]


In [39]:
import numpy as np
x=np.zeros([2,2]) # Creates an array of zeros with specified shape
print(x)

[[0. 0.]
 [0. 0.]]


In [7]:
import numpy as np
arr = np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [40]:
import numpy as np
vector = np.linspace( 0, 20, 5 ) # Returns numbers(float values) after every 5 numbers from 0 to 25
print(vector)
print(type(vector))


[ 0.  5. 10. 15. 20.]
<class 'numpy.ndarray'>


In [9]:
import numpy as np
x=[1,2,3]
a=np.asarray(x) # Converts list (x) into array
print(a)


[1 2 3]


In [45]:
import numpy as np
arr=np.zeros(4)
arr3d=arr.reshape((1,2,2)) # Reshapes the array into specified dimension
print(arr3d)

[[[0. 0.]
  [0. 0.]]]


In [9]:
import numpy as np
arr=np.zeros(8)
arr3d=arr.reshape((2,2,2))
arr=arr3d.ravel()
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [46]:
import numpy as np
arr=np.arange(2,20) 
print(arr)
element=arr[6]
print(element)


[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
8


In [22]:
import numpy as np
arr=np.arange(20)
arr_slice=slice( 1,10,2 ) # Slices numbers from 1 to 10 and returns values after stepping every 2 numbers
arr[arr_slice]

array([1, 3, 5, 7, 9])

In [48]:
import numpy as np
n=int(input("enter the value:"))
arr=np.arange(n)
print(arr[2:])

enter the value: 1500


[   2    3    4 ... 1497 1498 1499]


In [49]:
import numpy as np
arr=np.arange(20)
print(arr[:15])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [14]:
import numpy as np
a=np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a[0:2,0:2])

[[1 2]
 [3 4]]


In [50]:
import numpy as np
a=np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a.shape)
print(a.ndim)  # Returns the dimensions of an array
print(a.itemsize)  # Returns the size of an array in bytes

(3, 3)
2
4


In [56]:
import pandas as pd
listx = [10, 20, 30, 40]
table = pd.DataFrame(listx)
#table = pandas.DataFrame(listx)
print(table)

    0
0  10
1  20
2  30
3  40


In [57]:
import pandas
data = [{'a':1, 'b':2}, {'a':2, 'b':4, 'c':8}]
table = pandas.DataFrame(data)
print(table)
table

   a  b    c
0  1  2  NaN
1  2  4  8.0


a  b    c
0  1  2  NaN
1  2  4  8.0

In [27]:
import pandas
data = [{'a':1, 'b':2}, {'a':2, 'b':4, 'c':8}]
table = pandas.DataFrame(data, index=[ 'first', 'second' ])
print(table)

        a  b    c
first   1  2  NaN
second  2  4  8.0


In [59]:
import pandas
data = {'one': pandas.Series([1, 2, 3,], index=['a', 'b', 'c']),
        'two': pandas.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
table = pandas.DataFrame(data)
print(table)

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4


In [29]:
import pandas
data = {'one': pandas.Series([1, 2, 3], index=['a', 'b', 'c']),
        'two': pandas.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
table = pandas.DataFrame(data)
table['three'] = pandas.Series([10, 20, 30], index=['a', 'b', 'c'])  # Adding column "three"
print(table)

   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN


In [30]:
import pandas
data = {'one': pandas.Series([1, 2, 3], index=['a', 'b', 'c']),
        'two': pandas.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
table = pandas.DataFrame(data)
table['three'] = pandas.Series([10, 20, 30], index=['a', 'b', 'c'])
print(table)
print(table.loc['c']) # Returns  values of row "c"

   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN
one       3.0
two       3.0
three    30.0
Name: c, dtype: float64


In [31]:
import pandas
data = {'one': pandas.Series([1, 2, 3], index=['a', 'b', 'c']),
        'two': pandas.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
table = pandas.DataFrame(data)
table['three'] = pandas.Series([10, 20, 30], index=['a', 'b', 'c'])
print(table)
print(table.iloc[2])

   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN
one       3.0
two       3.0
three    30.0
Name: c, dtype: float64


In [36]:
import pandas as pd

# Create data
data = {
    'one': pd.Series([1, 2, 3], index=['a', 'b', 'c']),
    'two': pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
}
table = pd.DataFrame(data)

# Add a new column
table['three'] = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
print("Initial table:\n", table)

# Create new rows as DataFrame
row = pd.DataFrame([[11, 13], [17, 19]], columns=['two', 'three'])

# Append using concat (since append() is deprecated from latest)
table = pd.concat([table, row], ignore_index=True)
print("\nTable after appending rows:\n", table)


Initial table:
    one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN

Table after appending rows:
    one  two  three
0  1.0    1   10.0
1  2.0    2   20.0
2  3.0    3   30.0
3  NaN    4    NaN
4  NaN   11   13.0
5  NaN   17   19.0


In [55]:
arr=np.loadtxt('umesh_ml.txt')
np.savetxt('SAP_UMESH_ML',arr)